/**
 * Copyright 2016, GeoSolutions Sas.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree.
 */

module.exports = {
    plugins: {
        // mapstore product plugins
        AboutPlugin: require("../MapStore2/web/client/product/plugins/About"),
        AttributionPlugin: require("../MapStore2/web/client/product/plugins/Attribution"),
        FooterPlugin: require("../MapStore2/web/client/product/plugins/Footer"),
        ForkPlugin: require("../MapStore2/web/client/product/plugins/Fork"),
        HeaderPlugin: require("../MapStore2/web/client/product/plugins/Header"),
        HomePlugin: require('../MapStore2/web/client/plugins/Home'),
        HomeDescriptionPlugin: require("../MapStore2/web/client/product/plugins/HomeDescription"),
        LoginPlugin: require('../MapStore2/web/client/plugins/Login'),
        MapTypePlugin: require("../MapStore2/web/client/product/plugins/MapType"),
        NavMenu: require("../MapStore2/web/client/product/plugins/NavMenu"),
        // framework plugins
        AddGroupPlugin: require("../MapStore2/web/client/plugins/AddGroup").default,
        AnnotationsPlugin: require("../MapStore2/web/client/plugins/Annotations"),
        AutoMapUpdatePlugin: require("../MapStore2/web/client/plugins/AutoMapUpdate"),
        BackgroundSelectorPlugin: require("../MapStore2/web/client/plugins/BackgroundSelector"),
        BackgroundSwitcherPlugin: require("../MapStore2/web/client/plugins/BackgroundSwitcher"),
        BurgerMenuPlugin: require("../MapStore2/web/client/plugins/BurgerMenu"),
        ContentTabs: require("../MapStore2/web/client/plugins/ContentTabs"),
        CookiePlugin: require("../MapStore2/web/client/plugins/Cookie"),
        CreateNewMapPlugin: require("../MapStore2/web/client/plugins/CreateNewMap").default,
        Dashboard: require("../MapStore2/web/client/plugins/Dashboard"),
        DashboardEditor: require("../MapStore2/web/client/plugins/DashboardEditor"),
        DashboardSavePlugin: require('../MapStore2/web/client/plugins/DashboardSave').DashboardSave,
        DashboardSaveAsPlugin: require('../MapStore2/web/client/plugins/DashboardSave').DashboardSaveAs,
        DashboardsPlugin: require("../MapStore2/web/client/plugins/Dashboards"),
        DetailsPlugin: require("../MapStore2/web/client/plugins/Details"),
        DrawerMenuPlugin: require("../MapStore2/web/client/plugins/DrawerMenu"),
        ExamplesPlugin: require('../MapStore2/web/client/product/plugins/Examples'),
        ExpanderPlugin: require("../MapStore2/web/client/plugins/Expander"),
        FeaturedMaps: require("../MapStore2/web/client/plugins/FeaturedMaps"),
        FeatureEditorPlugin: require("../MapStore2/web/client/plugins/FeatureEditor").default,
        FeedbackMaskPlugin: require("../MapStore2/web/client/plugins/FeedbackMask"),
        FilterLayerPlugin: require('../MapStore2/web/client/plugins/FilterLayer').default,
        FloatingLegendPlugin: require("../MapStore2/web/client/plugins/FloatingLegend"),
        FullScreenPlugin: require("../MapStore2/web/client/plugins/FullScreen"),
        GlobeViewSwitcherPlugin: require("../MapStore2/web/client/plugins/GlobeViewSwitcher"),
        GoFull: require("../MapStore2/web/client/plugins/GoFull"),
        GroupManagerPlugin: require('../MapStore2/web/client/plugins/manager/GroupManager'),
        GridContainerPlugin: require("../MapStore2/web/client/plugins/GridContainer"),
        HelpLinkPlugin: require("../MapStore2/web/client/plugins/HelpLink").default,
        HelpPlugin: require("../MapStore2/web/client/plugins/Help"),
        IdentifyPlugin: require("../MapStore2/web/client/plugins/Identify"),
        LanguagePlugin: require("../MapStore2/web/client/plugins/Language"),
        LayerInfoPlugin: require('..MapStore2/web/client/plugins/LayerInfo').default,
        LocatePlugin: require("../MapStore2/web/client/plugins/Locate"),
        ManagerMenuPlugin: require('../MapStore2/web/client/plugins/manager/ManagerMenu'),
        MapExportPlugin: require('../MapStore2/web/client/plugins/MapExport').default,
        MadeWithLovePlugin: require('../MapStore2/web/client/product/plugins/MadeWithLove'),
        MapFooterPlugin: require("../MapStore2/web/client/plugins/MapFooter"),
        MapImportPlugin: require("../MapStore2/web/client/plugins/MapImport"),
        MapLoadingPlugin: require("../MapStore2/web/client/plugins/MapLoading"),
        MapPlugin: require("../MapStore2/web/client/plugins/Map"),
        MapSearchPlugin: require("../MapStore2/web/client/plugins/MapSearch"),
        MapsPlugin: require("../MapStore2/web/client/plugins/Maps"),
        MeasurePlugin: require("../MapStore2/web/client/plugins/Measure"),
        MetadataExplorerPlugin: require("../MapStore2/web/client/plugins/MetadataExplorer"),
        MousePositionPlugin: require("../MapStore2/web/client/plugins/MousePosition"),
        NotificationsPlugin: require("../MapStore2/web/client/plugins/Notifications"),
        OmniBarPlugin: require("../MapStore2/web/client/plugins/OmniBar"),
        PlaybackPlugin: require("../MapStore2/web/client/plugins/Playback.jsx"),
        PrintPlugin: require("../MapStore2/web/client/plugins/Print"),
        QueryPanelPlugin: require("../MapStore2/web/client/plugins/QueryPanel"),
        RedirectPlugin: require("../MapStore2/web/client/plugins/Redirect"),
        RedoPlugin: require("../MapStore2/web/client/plugins/History"),
        RulesToolbarPlugin: require('../MapStore2/web/client/plugins/manager/RulesToolbar'),
        RulesDataGridPlugin: require("../MapStore2/web/client/plugins/RulesDataGrid"),
        RulesEditorPlugin: require("../MapStore2/web/client/plugins/RulesEditor"),
        RulesManagerFooter: require("../MapStore2/web/client/plugins/RulesManagerFooter"),
        SaveAsPlugin: require("../MapStore2/web/client/plugins/SaveAs").default,
        SavePlugin: require("../MapStore2/web/client/plugins/Save").default,
        ScaleBoxPlugin: require("../MapStore2/web/client/plugins/ScaleBox"),
        ScrollTopPlugin: require("../MapStore2/web/client/plugins/ScrollTop"),
        SearchPlugin: require("../MapStore2/web/client/plugins/Search"),
        SearchServicesConfigPlugin: require("../MapStore2/web/client/plugins/SearchServicesConfig"),
        SearchByBookmarkPlugin: require('../MapStore2/web/client/plugins/SearchByBookmark').default,
        SettingsPlugin: require("../MapStore2/web/client/plugins/Settings"),
        SharePlugin: require("../MapStore2/web/client/plugins/Share"),
        SnapshotPlugin: require("../MapStore2/web/client/plugins/Snapshot"),
        StyleEditorPlugin: require("../MapStore2/web/client/plugins/StyleEditor"),
        ThematicLayerPlugin: require("../MapStore2/web/client/plugins/ThematicLayer"),
        ThemeSwitcherPlugin: require("../MapStore2/web/client/plugins/ThemeSwitcher"),
        TimelinePlugin: require("../MapStore2/web/client/plugins/Timeline"),
        TOCItemsSettingsPlugin: require("../MapStore2/web/client/plugins/TOCItemsSettings").default,
        TOCPlugin: require("../MapStore2/web/client/plugins/TOC"),
        ToolbarPlugin: require("../MapStore2/web/client/plugins/Toolbar"),
        TutorialPlugin: require("../MapStore2/web/client/plugins/Tutorial"),
        UserManagerPlugin: require('../MapStore2/web/client/plugins/manager/UserManager'),
        UndoPlugin: require("../MapStore2/web/client/plugins/History"),
        VersionPlugin: require("../MapStore2/web/client/plugins/Version"),
        WFSDownloadPlugin: require("../MapStore2/web/client/plugins/WFSDownload"),
        WidgetsTrayPlugin: require('../MapStore2/web/client/plugins/WidgetsTray'),
        WidgetsPlugin: require("../MapStore2/web/client/plugins/Widgets").default,
        WidgetsBuilderPlugin: require("../MapStore2/web/client/plugins/WidgetsBuilder").default,
        ZoomAllPlugin: require("../MapStore2/web/client/plugins/ZoomAll"),
        ZoomInPlugin: require("../MapStore2/web/client/plugins/ZoomIn"),
        ZoomOutPlugin: require("../MapStore2/web/client/plugins/ZoomOut"),
        // project plugins
        DateFilter: require('./plugins/DateFilter'),
        IdentifySettingsPlugin: require('./plugins/IdentifySettings')
    },
    requires: {
        ReactSwipe: require('react-swipeable-views').default,
        SwipeHeader: require('../MapStore2/web/client/components/data/identify/SwipeHeader')
    }
};
