version: '3.1'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        # - ./nginx/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
        # - ./nginx/comodo/STAR_geo-solutions.it.key:/etc/ssl/certs/STAR_geo-solutions.it.key
        # - ./nginx/comodo/STAR_geo-solutions.it.pem:/etc/ssl/certs/STAR_geo-solutions.it.pem
    secrets:
      - STAR_geo-solutions.it.key
      - STAR_geo-solutions.it.pem
      - dhparam-2048.pem

  austrocontrol:
    image: geosolutionsit/austrocontrol:latest
    ports:
      - "8080"
    environment:
      JAVA_OPTS: -Xms1024m -Xmx1024m -Dgeostore-ovr=file:///usr/local/tomcat/conf/geostore-datasource-ovr.properties -XX:+UseConcMarkSweepGC -DMAPFISH_PDF_FOLDER=/tmp
    volumes:
      - ./austrocontrol/geostore-datasource-ovr.properties:/usr/local/tomcat/conf/geostore-datasource-ovr.properties
    extra_hosts:
      - "dbms2.geo-solutions.it:192.168.1.100"

secrets:
  STAR_geo-solutions.it.key:
    external: true
  STAR_geo-solutions.it.pem:
    external: true
  dhparam-2048.pem:
    external: true

